### ISSUE TITLE
[POSIX] sleep only takes int

### ISSUE THREAD

**Issue by astralchan** [n-ivkovic/tspreed#11]
POSIX compliant `sleep` only takes positive intergers. See [here](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sleep.html#top). I was going to make a PR to change the last `sleep 0.75` to `sleep 1`, but another issue is how `delay` is handled via `sleep`. I don't know how one would fix it to be POSIX compliant.

**Comment by n-ivkovic** [comment]
Thanks for notifying me of this issue, this has now been fixed in 5411c5de0ba9fe08984e97f66f5f4de06e4e973e. Unfortunately, the only real solution is quite inefficient and is simply while loop that does nothing until enough time has elapsed. More than happy to look into other solutions suggested. As a compromise I've added an option to allow POSIX compliance to be broken and use a float as the time operand in `sleep(1)`, which is non-standard behavior however supported by major implementations of `sleep(1)`
