### ISSUE TITLE
FEAT: Pause, Back, Resume

### ISSUE THREAD

**Issue by pylang** [n-ivkovic/tspreed#3]
Appreciate the tool.

I heard about some [suggestions](https://www.youtube.com/watch?v=3WL-zbWZvN8&t=475s) that I'd appreciate as well:

- Pause/Resume: stop and start at a position (perhaps space bar)
- Back: move back a few words and continue (nav keys)

I think the options we have now are Ctrl + C to stop and re-enter the position to resume or go back.  This works, but having direct keybindings might make transitioning in and out of focus mode smoother.

**Comment by astralchan** [comment]
This would be very cool to see. Being a POSIX shell script, perhaps one way to implment it would be a case block for `input` defined as
```sh
while :
do
    read -rsn1 input
    case "$input" in
        " ") <pause function> ;;
        "h") <backward function> ;;
        "l") <forward function> ;;
    esac
done
```
I'm not too sure myself how one would go about implementing the functions. `tput` seems to be the main function that actually puts text on the screen as far as I know. I'm not too familiar wih `tput` myself.

**Comment by n-ivkovic** [comment]
Sorry it took me way too long to address this, but better late than never as they say!

I've committed f13945c31df68c7afe131cb5dc1930feb4e1ece9 to develop which adds keyboard controls, including pausing/resuming the presentation. Pausing/resuming is mapped to the `P` key for now.

Skipping backward/forward isn't something I can feasibly include in the script with the way it's built now, but I may revisit this another day.

All the non POSIX-compliant `read` options that are required to include keyboard controls (-s to disable output, -n to limit the number of characters read, and -t to specify a timeout in fractional seconds) are only supported by Bash's `read` builtin as far as I can tell. As such, tspreed will need to be run via Bash in order to take advantage of keyboard controls. If your `/bin/sh` is not symlinked to Bash, this can be done by either calling the tspreed script via Bash (`$ bash tspreed`) or updating the shebang to point to Bash.

This change is on track to be merged into master, however I'd like to test this change a bit more before doing so. There's also a couple changes I'd like to look into while I'm working on tspreed again before I merge into master a create a new release.
